### ISSUE TITLE
(SURE-4646) Rancher deletes unmanaged objects

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#100]
#### Issue description:

Rancher deletes VNET created outside of Rancher upon cluster deletion if VNET is empty

#### Business impact:

We have managment VNET by terraform and some peering in our onprem networks manualy by Network Team. So in that case if Rancher delete VNET, we need recreate this, and Network Team need repair peering.

#### Reproduction steps:

Delete AKS cluster using VNET not created by Rancher but only used by Rancher AKS cluster

Customer reports these are the steps taken:

1) Create VNET on Azure with Terraform
2) Create new kubernetes cluster with Terraform and import as a downstream cluster into Rancher
3) Delete imported downstream cluster and see VNET destroyed

#### Workaround:
Recommended that customer tag VNET objects to skip deletion, but they said locking resources in azure would be problematic.

#### Actual behavior:
Rancher deletes VNET objects if there are no resources using it after a cluster is deleted

#### Expected behavior:
Rancher ignores Azure VNET objects not created by Rancher

**Comment by kkaempf** [comment]
Needs to be tested with 2.7.2

**Comment by mjura** [comment]
I have retested everything once again with Rancher v2.7.2 and AKSv2 driver and for imported managed clusters we don't remove anything from managed environment. I assume that this bug was reported for Rancher v.2.5.7 where KEv1 was used, which is deprecated.

 

Please use latest version of Rancher v2.7.2 and import cluser with AKSv2 driver which is mandatory for that version of Rancher. After it everything will work fine and no resources from Azure will be deleted.
