### ISSUE TITLE
Unable to deploy AKS cluster due to Rancher generating and appending characters to the node resource group which is too long.

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#207]
### Issue description:
Customer is unable to deploy AKS cluster due to Rancher generating and appending characters to the cluster name 

### Business impact:
Unable to deploy AKS cluster using Rancher. 

### Troubleshooting steps:
From Rancher UI we do not have an option to provide a node resource group name. Rancher in the backend automatically generates characters and appends them with the name provided in the cluster resource group and creates a node resource group name that is too long. 
~~~
Error failed to create cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="The length of the node resource group name is too long. The maximum length is 80 and the length of the value provided is 87. Please see https://aka.ms/aks-naming-rules for more details." Target="name" 
~~~
We can create an AKS cluster with a shorter name but this is against the naming conventions of CLASS infrastructure.  Example the resource-group CLASS specified was "RG-Test-Kafka-RemoteService-AKS-3". Rancher generates characters with cluster name and region name (MC_RG-Test-Kafka-RemoteService-AKS-3_<ClusterName>_<Region>) which becomes too long and the cluster deployment fails. 

### Repro steps:

Create an AKS cluster with a longer name and also provide a larger cluster resource group name. This will fail the cluster deployment. 

### Workaround:
Is a workaround available and implemented? yes  
What is the workaround: To provide a shorter name but this cannot be implemented as its against the CLASS naming convention. 

### Actual behavior:
The customer is unable to deploy AKS cluster due to Rancher generating and appending characters to the node resource group which is too long.

### Expected behavior:
Rancher should provide an option to pass the node resource group name in the Rancher UI while deploying AKS cluster. This option is available in Azure CLI method and the customer is expecting the same from the Rancher side.

**Comment by kkaempf** [comment]
we have to add the feature to allow passing the node resource group name in the aks-operator and then have a field in the UI for users to input this custom name

**Comment by kkaempf** [comment]
Corresponding to rancher/dashboard#8980

**Comment by salasberryfin** [comment]
Just discussed potential solutions on the operator side with @mjura and we'll take a look at this.

**Comment by salasberryfin** [comment]
A PR with the fix was merged but there are two parts to the changes and one of them is pending changes in the UI (rancher/dashboard#8980):
- **Done** - Fix the issue of Azure node resource group names being too long: this is now fixed and names should be truncated to a maximum of 80 characters.
- **Blocked** - Let users provide a custom node resource group name: a new field was added to the cluster specification in the `aks-operator` and this requires a new option in the UI to make this configurable.

So this bug is fixed: a resource group name will be generated by Azure and truncated by Rancher if it exceeds the character. To allow the user to input their own resource group name, we need to include such configuration field in the UI rancher/dashboard#8980

**Comment by cpinjani** [comment]
Validation Done: https://github.com/rancher/dashboard/issues/8980#issuecomment-1652270457
