### ISSUE TITLE
Deprecate 'Docker bridge address' field

### ISSUE THREAD

**Issue by cpinjani** [rancher/aks-operator#248]
**Rancher version:**
```
v2.7-0b2f7fa0f878c3402ddf416a5b622327949b9348-head
aks-operator:v1.1.3-rc1
```
Cluster Type: Downstream AKS cluster

**Describe the bug**
Docker Bridge CIDR field has been removed from AKS API. (Ref: https://github.com/Azure/AKS/releases/tag/2023-05-07)
The same can be deprecated from AKS operator

Found while validating https://github.com/rancher/rancher/issues/42496

## PR's:
- [x] https://github.com/rancher/aks-operator/pull/521
- [x] https://github.com/rancher/aks-operator/pull/520

**Comment by salasberryfin** [comment]
After discussing the deprecation of the field with @mjura, this will have to be addressed as part of #287. We're currently using an older version of the AKS API that's still using Docker Bridge CIDR and we'll need to update this before removing the option.

**Comment by yiannistri** [comment]
The migration to the new Azure SDK is now done for the v2.9 branch. But I don't think it's worth introducing a new CRD version that does not include this field in order to deprecate it. I suggest we remove any logic that relies on this field (i.e. validation) and update the docs to reflect that this field is no longer used. I'm not sure whether this work should happen only on v2.9 or in all currently supported versions. Thoughts @mjura @salasberryfin ?

**Comment by mjura** [comment]
> The migration to the new Azure SDK is now done for the v2.9 branch. But I don't think it's worth introducing a new CRD version that does not include this field in order to deprecate it. I suggest we remove any logic that relies on this field (i.e. validation) and update the docs to reflect that this field is no longer used. I'm not sure whether this work should happen only on v2.9 or in all currently supported versions. Thoughts @mjura @salasberryfin ?

Only for `v2.9`

**Comment by mjura** [comment]
it is done
