### ISSUE TITLE
Rancher cannot import AKS behind http-proxy & vpn connection to Azure

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#256]
### Issue description:

Rancher  provisions the AKS cluster using the UI, but it does not finish importing it correctly to Rancher. On the Rancher UI , the AKS cluster is stuck on "waiting for API to be available"

### Business impact:

Cannot manage AKS clusters from Rancher UI, as the cluster is created but not successfully imported into Rancher. The service account token for the sa "cattle" isn't created.

### Troubleshooting steps:
**

Provisioned an AKS cluster on a different region using Azure Console, and importing into Rancher -> KO
Provision an AKS cluster on a different region using Rancher UI -> KO, cluster is provisioned but not imported into Rancher
Create the "cattle" serviceaccount token with kubectl commands, as this is not created during Rancher agent deployment, but the cattle-cluster-agent pods isn't aware of it.

### Repro steps:

Setup an AKS cluster using Rancher UI.
AKS Cluster settings: Attached cluster.yml
AKS cluster is pending API to be available, due to no serviceaccount token is created during the Rancher-agent deployment on the AKS cluster.

### Workaround:
Is a workaround available and implemented? yes
What is the workaround: Add the following parameters to the cattle-cluster-agent deployment, it will remain stable, however, any other operation/installation on the cluster, fails due to no connectivity to the AKS API.

### Actual behavior:

AKS cluster is not manageable through Rancher, either Rancher-provisioned or Rancher-imported

### Expected behavior:

Service account "cattle"'s token is created, the cattle-cluster-agent can talk to the API and the AKS is imported successfully.

### Files, logs, traces:

Attached Rancher pod logs, Aks-operator logs, cluster.yml and

**Comment by DevOpsNewbie** [comment]
Environmental issue, customer confirmed it:

Since yesterday we were able to solve the issue with Microsoft support.

There are two different firewall rule collection types:
" Application rule collection (filters FQDNs)
" Network rule collection (filters based on IPs)
 
We already had an application rule in place.
Based on this we assumed in the past, that this rule (source ip: *, dest fqdn: *, port 443) should be enough to communicate from Kubernetes pods to our API. But we were wrong.
After adding an additional network rule collection, all pods were able to access the API through the public address.

So it has never been an issue within Rancher or how Rancher accessed the AZure API.
