### ISSUE TITLE
[Feature] K8s 1.27 support

### ISSUE THREAD

**Issue by vardhaman22** [rancher/aks-operator#269]
issue: https://github.com/rancher/rancher/issues/41840

- k8s deps bump to 0.27.x required.
- bump rancher machine to v0.15.0-rancher103
- need to use latest 1.5.0 rc tag available for rke
- other dependencies
```
github.com/rancher/wrangler v1.1.1-0.20230831050635-df1bd5aae9df
github.com/rancher/lasso v0.0.0-20230830164424-d684fdeb6f29
github.com/rancher/fleet/pkg/apis v0.0.0-20230901075223-437edb7091f5
github.com/rancher/norman v0.0.0-20230831160711-5de27f66385d
```
- after that new changes needs to be vendored in rancher

**Comment by mjura** [comment]
@vardhaman22, @mitulshah-suse hi, can you please tell us how did you generated version for these modules, because https://github.com/rancher/rancher/blob/release/v2.8/go.mod is still using older versions of them.

Bumping versions for all these modules will also impact Rancher v2.8, because Rancher is including AKS/GKE/EKS operators as go modules.

**Comment by rayandas** [comment]
@mjura For K8s v1.27 upgrade, we bumped all of these and the PR for rancher is pending because of CI failure. https://github.com/rancher/rancher/pull/42389 
When it gets merged, 2.8 will use the same ones.

**Comment by cpinjani** [comment]
Can we merge PRs since https://github.com/rancher/rancher/pull/42808 is merged ?

**Comment by vardhaman22** [comment]
Hi @cpinjani, yes PRs can be merged.

**Comment by kkaempf** [comment]
closing
