### ISSUE TITLE
[v2.9] Error in logs while updating cluster tags

### ISSUE THREAD

**Issue by cpinjani** [rancher/aks-operator#508]
**Rancher version:**
v2.9-6d87a11ea46b7571646d7c3d7af704584c39fd62-head
aks-operator:v1.3.0-rc11

**Describe the bug**
While updating tags for cluster, there is message in logs "Tags were not updated as expected", however tags gets updated successfully

**Logs**
```
time="2024-05-06T08:53:48Z" level=info msg="Checking configuration for cluster [cpinjani-aks]"
time="2024-05-06T08:53:49Z" level=info msg="Updating tags for cluster [cpinjani-aks]"
time="2024-05-06T08:53:53Z" level=info msg="Tags were not updated as expected for cluster [cpinjani-aks], expected map[Account Owner:<REDACTED> Account Type:group Cost Center:<REDACTED> Department:<REDACTED> Environment:development Finance Business Partner:<REDACTED> General Ledger Code:<REDACTED> Stakeholder:<REDACTED> Team:<REDACTED> k1:v1], actual map[Account Owner:<REDACTED> Account Type:group Cost Center:<REDACTED> Department:<REDACTED> Environment:development Finance Business Partner:<REDACTED> General Ledger Code:<REDACTED> Stakeholder:<REDACTED> Team:<REDACTED> k1:v1], moving on"
time="2024-05-06T08:53:53Z" level=info msg="Configuration for cluster [cpinjani-aks] was verified"
```

**PR**
- [x] https://github.com/rancher/aks-operator/pull/535
- [x] https://github.com/rancher/aks-operator/pull/536
- [x] https://github.com/rancher/aks-operator/pull/537

**Comment by mjura** [comment]
@cpinjani It is not a bug or error. It is because  Azure may have a policy that automatically adds upstream default tags to a cluster resource. We don't have a good way to detect that policy. We handle this case by checking if Azure returns an unexpected state for the tags and if so, log the response and move on. Any upstream tags regenerated on the cluster by Azure will be synced back to rancher.

I have submitted small adjustment to log message.
