### ISSUE TITLE
When an operation is triggered from azure and in progress, any operation triggered from Rancher is omitted

### ISSUE THREAD

**Issue by valaparthvi** [rancher/aks-operator#676]
**Versions:**
- Rancher: v2.9-9cec8a218821a7f4b89ff4882425647fe89a2963-head
- Operator:  rancher-aks-operator:104.3.0+up1.9.3-rc.1 

**Steps to reproduce:**
1. For a rancher-provisioned/imported AKS cluster, trigger an update from Azure console, e.g. scaling a nodepool.
2. While the update is in progress, trigger an update from Rancher Dashboard, e.g. add a nodepool

**Actual Results:**
The following message appears in the operator logs:
```
time="2024-10-07T09:38:46Z" level=info msg="Waiting for non-Rancher initiated cluster update for [pvala-aks-sync (id: c-4759x)]"
```

The update from the Azure console appears on Rancher dashboard after it completes, but the Rancher-triggered update is discarded.

**Expected Results:**
Once the update from the Azure console completes, the Rancher-triggered update must be put into action. If this is not possible, then an error message must appear on Dashboard saying that user needs to wait until non-rancher initiated update completes before attempting to update.

**Other Notes:**
If k8s upgrade from Azure is triggered to vX+1, and k8s upgrade from Rancher is triggered to vX+2, the following message appears in logs, but rancher-triggered upgrade goes through once azure-triggered upgrade completes.
```
time="2024-10-07T10:27:18Z" level=info msg="Updating kubernetes version to 1.28.11 for cluster [pvala-aks-sync (id: c-4759x)]"
time="2024-10-07T10:27:25Z" level=error msg="can't update the AKS cluster with error: PUT https://management.azure.com/subscriptions/80de5134-ca65-4731-be21-13fb1f0910a2/resourceGroups/pvala-aks-rg/providers/Microsoft.ContainerService/managedClusters/pvala-aks-sync\n--------------------------------------------------------------------------------\nRESPONSE 409: 409 Conflict\nERROR CODE: OperationNotAllowed\n--------------------------------------------------------------------------------\n{\n  \"code\": \"OperationNotAllowed\",\n  \"details\": null,\n  \"message\": \"Operation is not allowed: Another operation (Upgrading) is in progress, please wait for it to finish before starting a new operation. See https://aka.ms/aks-pending-operation for more details. The previous operation started at '2024-10-07T10:25:36Z' and elapsed time is: '00:01:48' (RFC3339 format)\",\n  \"subcode\": \"\"\n}\n--------------------------------------------------------------------------------\n"
time="2024-10-07T10:27:25Z" level=error msg="error syncing 'cattle-global-data/c-4759x': handler aks-controller: failed to update cluster: PUT https://management.azure.com/subscriptions/80de5134-ca65-4731-be21-13fb1f0910a2/resourceGroups/pvala-aks-rg/providers/Microsoft.ContainerService/managedClusters/pvala-aks-sync\n--------------------------------------------------------------------------------\nRESPONSE 409: 409 Conflict\nERROR CODE: OperationNotAllowed\n--------------------------------------------------------------------------------\n{\n  \"code\": \"OperationNotAllowed\",\n  \"details\": null,\n  \"message\": \"Operation is not allowed: Another operation (Upgrading) is in progress, please wait for it to finish before starting a new operation. See https://aka.ms/aks-pending-operation for more details. The previous operation started at '2024-10-07T10:25:36Z' and elapsed time is: '00:01:48' (RFC3339 format)\",\n  \"subcode\": \"\"\n}\n--------------------------------------------------------------------------------\n, requeuing"
```

We need a more concise definition of how the sync works between Azure and Rancher. Currently, the behavior is confusing. The behavior is inconsistent, e.g. if Azure triggered action is k8s upgrade, adding a nodepool from rancher seems to trigger k8s upgrade instead.

**Comment by valaparthvi** [comment]
When a rancher-initiated action is triggered in parallel to a non-rancher-initiated action, the cluster sometimes does not go into the `Updating` state as it should, even if it succeeds.

**Comment by valaparthvi** [comment]
Sync operation seems to behave differently when rancher-initiated action is triggered via API.
E.g. for a cluster with multiple nodepools: agentpool, poo1, pool2, and pool3.
1. Delete pool2 from Azure console.
2. While the deletion is in progress, delete pool3 from rancher.
3. Wait for a few minutes

When this is done via UI, pool2 is restored, but when done via API, pool2 stays deleted, and pool3 deletion is ignored.

**Comment by yiannistri** [comment]
I was able to reproduce this issue. However, I believe this is related to how [syncing](https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/sync-clusters) in Rancher works. Let me try to explain why I think that is.

In addition to the controller that attempts to reconcile the desired spec with the cloud provider, Rancher does a refresh of the current spec at a specified interval, set by default to 5 mins. This is the indirect mechanism that allows the operator to detect any changes that happen on the cloud provider side, and attempt to reconcile them. You can see this in action, by enabling debug logs for the Rancher pod and then grepping the log output:

```
kubectl logs -n cattle-system deployments/rancher -f | grep -A 2 -i 'checking cluster'
```

If there is no change on the cloud provider side, you should see logs similar to these:

```
2024/10/21 14:15:31 [DEBUG] checking cluster [c-z5d2l] upstream state for changes
2024/10/21 14:15:33 [DEBUG] updating cluster [c-z5d2l], upstream change detected
2024/10/21 14:15:33 [DEBUG] cluster [c-z5d2l] matches upstream, skipping spec sync
```

The last log line indicates that cluster spec matches upstream so there's nothing to do/update.

However, if there is a change on the cloud provider, Rancher will refresh the spec accordingly.

```
2024/10/21 14:25:35 [DEBUG] checking cluster [c-z5d2l] upstream state for changes
2024/10/21 14:25:36 [DEBUG] updating cluster [c-z5d2l], upstream change detected
2024/10/21 14:25:36 [DEBUG] change detected for cluster [c-z5d2l], updating spec
```

At that point, the spec changes, the controller detects the spec has changed and runs its reconcile loop again. Since the spec is up-to-date, the controller typically will do nothing as shown in its logs:

```
INFO[1162] Checking configuration for cluster [yiannis-aks-01 (id: c-z5d2l)]
INFO[1163] Configuration for cluster [yiannis-aks-01 (id: c-z5d2l)] was verified
```

So far we have established that the controller begins its reconcile loop when there is a change in the spec (either via a user changing the cluster in Rancher UI or via a change on the cloud provider side at a specified interval) and that the controller uses (almost) up-to-date information about the cluster's state.

Let's explore the scenario when a change happens in Rancher right after a change has happened upstream. Assuming those changes happen at around the same time and Rancher has not refreshed the spec in between those changes, the controller will detect the Rancher change and attempt to reconcile it. Currently, the controller [checks](https://github.com/rancher/aks-operator/blob/3721b2c9f57578e5732cc7a12d9f81de93e0ebb8/controller/aks-cluster-config-handler.go#L307-L313) the status of the cluster upstream and if it's in progress or updating, it will log a line indicating that a change has happened upstream (`Waiting for non-Rancher initiated cluster update ...`) and return without any errors.

**Comment by valaparthvi** [comment]
>In short, the last write wins.

Do you mean the first write?

> This is very likely the main reason we've put this note in our docs, which I didn't quite fully understand up until now.

It does sum up all that you explained. Thank you for looking into this. I think we will need to modify our tests to take this behavior into account.

My takeaway is to avoid simultaneous change if possible.

**Comment by valaparthvi** [comment]
>If k8s upgrade from Azure is triggered to vX+1, and k8s upgrade from Rancher is triggered to vX+2, the following message appears in logs, but rancher-triggered upgrade goes through once azure-triggered upgrade completes.

What is your take on this @yiannistri?

**Comment by yiannistri** [comment]
> Do you mean the first write?

I meant the last write because every time the spec gets updated (however this may happen) the controller will start a reconcile loop and use the spec (and status) as the source of truth for applying any changes. So whichever process happens to write to the spec last, it is the changes of that process that will be applied eventually.
 
> My takeaway is to avoid simultaneous change if possible.

Yeah I think that would be sensible. I am very aware that the way this works currently can cause issues for some users but it appears that this was build this way on purpose (whatever that purpose was).

**Comment by kkaempf** [comment]
@mjura shouldn't this be scheduled for 2.9.x instead ? 🤔

**Comment by mjura** [comment]
> @mjura shouldn't this be scheduled for 2.9.x instead ? 🤔

@yiannistri  @valaparthvi It is not issue, it is the way how in Rancher we treat source of true. There always some cases when users have to decide in which way they want to apply changes to cluster configuration. Rancher with hosted providers works as orchestration to another orchestration in Public cloud. Public Clouds they automating more and more stuff and we will have to decide which configuration is the correct one. In the Rancher case users have to ensure that there are no changes applied on Cloud Provider site and apply then with Rancher. Eventually repeat this operation once again. For CAPI it will work in this same way.

**Comment by mjura** [comment]
@yiannistri As solution to this I would go and update documentation comment which we have already.

**Comment by valaparthvi** [comment]
>It is not issue, it is the way how in Rancher we treat source of true. There always some cases when users have to decide in which way they want to apply changes to cluster configuration. Rancher with hosted providers works as orchestration to another orchestration in Public cloud. Public Clouds they automating more and more stuff and we will have to decide which configuration is the correct one. In the Rancher case users have to ensure that there are no changes applied on Cloud Provider site and apply then with Rancher. Eventually repeat this operation once again. For CAPI it will work in this same way.

@mjura We have test cases checking things such as:
- editing same/different fields from rancher and cloud console simultaneously
- deleting nodepool from cloud console, and editing the same nodepool from rancher
- upgrading k8s version simultaneously from both rancher and cloud console to same/different versions

Are these test cases not valid then?

**Comment by valaparthvi** [comment]
>As QA test cases to check if there are some errors, I would say that they are valid. But from production real user experience they are not, since we always tell users to use Rancher for managing downstream cluster if it was created from Rancher and for imported clusters always pick one source of true and don't reconfiguration from both places otherwise you will see a lot of race conditions.

Okay. Keeping in mind that users are advised to choose one source of truth, I think it would make sense for us to test and automate that if changes made from the cloud console are reflected back to Rancher, rather than spending time, fighting race conditions with these simultaneous changes.

**Comment by valaparthvi** [comment]
Considering that we already warn users about race conditions occurring on simultaneous changes, this is a known issue that we don't intend to fix.

We (QA) have refactored our test suite to include more real-time test cases (make changes from Cloud console and ensure they are synced back to Rancher) and removed tests related to this issue (simultaneous changes from both Rancher and cloud console).

Thanks, Yiannis for your deep dive on this issue, it was enlightening, and Michal for your final input.
