### ISSUE TITLE
(SURE-5510) Unable to upgrade an imported AKS cluster from Rancher GUI

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#93]
https://jira.suse.com/browse/SURE-5510

**Comment by mjura** [comment]
I will triage this card

**Comment by mjura** [comment]
This issue is missing basic data with information on customer AKS cluster configuration. As I mentioned in https://jira.suse.com/browse/SURE-5510

I have tried to check out this problem on our site with Rancher v2.6.8 Azure AKS supported versions currently are

KubernetesVersion    Upgrades
-------------------  -----------------------
1.25.5               None available
1.25.4               1.25.5
1.24.9               1.25.4, 1.25.5
1.24.6               1.24.9, 1.25.4, 1.25.5
1.23.15              1.24.6, 1.24.9
1.23.12              1.23.15, 1.24.6, 1.24.9

I did test upgrade from 1.23.12 to 1.23.15. Cluster was upgrade successfully.


What is missing for this bug is:

cluster.management.cattle.io YAML manifest from customer cluster
aksclusterconfigs.aks.cattle.io YAML manifest from customer cluster
Resource JSON from Azure Portal to customer cluster
 

Please provide us these information, otherwise we will be not able reproduce this problem on our site.

**Comment by mjura** [comment]
it is waiting for customer response

**Comment by kkaempf** [comment]
> it is waiting for customer response

See SURE-5510 😉

**Comment by mjura** [comment]
Finally we have got at least part of configuration, so I am starting investigation

**Comment by mjura** [comment]
Currently on Rancher v2.6.8 I am getting following error during upgrading:
```
time="2023-03-05T16:57:14Z" level=error msg="error syncing 'cattle-global-data/c-xb46v': handler aks-controller: failed to update cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code=\"LinkedAuthorizationFailed\" Message=\"The client 'bb491dd0-5d05-40c3-970d-ba80d0cf072b' with object id 'bb491dd0-5d05-40c3-970d-ba80d0cf072b' has permission to perform action 'Microsoft.ContainerService/managedClusters/write' on scope '/subscriptions/f5e1bf9e-ec79-4fc5-8354-53e2fcc0d99f/resourceGroups/mjura-aks/providers/Microsoft.ContainerService/managedClusters/mjura-test2'; however, it does not have permission to perform action 'Microsoft.OperationalInsights/workspaces/sharedkeys/read' on the linked scope(s) '/subscriptions/f5e1bf9e-ec79-4fc5-8354-53e2fcc0d99f/resourcegroups/defaultresourcegroup-eus/providers/microsoft.operationalinsights/workspaces/defaultworkspace-f5e1bf9e-ec79-4fc5-8354-53e2fcc0d99f-eus' or the linked scope(s) are invalid.\", requeuing"
```
